services:
  # client:
  #   build:
  #     context: ./frontend/MicroBiteClient
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend/MicroBiteClient:/app
  #     - /app/node_modules
  #   environment:
  #     VITE_AUTH_BASE_URL: http://localhost:5095/api
  #     VITE_RES_BASE_URL: http://localhost:5247/api
  #   depends_on:
  #     - auth-api
  #     - res-api

  # auth-api:
  #   build:
  #     context: ./backend/AuthServer
  #   ports:
  #     - "5095:5095"
  #   volumes:
  #     - ./backend/AuthServer/dataProtectionKeys:/root/.aspnet/DataProtection-Keys
  #   environment:
  #     ConnectionStrings__AuthDb: Host=auth-db;Port=5432;Database=MicroBiteAuth;Username=postgres;Password=1q2w3e
  #   depends_on:
  #     - auth-db
  
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: MicroBiteAuth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
    ports:
      - "15432:5432"
    volumes:
      - ./data/pg-auth-data/data:/var/lib/postgresql/data
      - ./data/pg-auth-data/app:/app
    working_dir: /app
  
  # res-api:
  #   build:
  #     context: ./backend/ResourceServer
  #   ports:
  #     - "5247:5247"
  #   volumes:
  #     - ./backend/ResourceServer/dataProtectionKeys:/root/.aspnet/DataProtection-Keys
  #   environment:
  #     ConnectionStrings__ResourceDb: Host=res-db;Port=5432;Database=MicroBiteResources;Username=postgres;Password=1q2w3e
  #     JwtSettings__JwksUrl: http://auth-api:5095/api/.well-known/jwks.json
  #   depends_on:
  #     - res-db
  #     - auth-api
  
  res-db:
    image: postgres:16
    environment:
      POSTGRES_DB: MicroBiteResources
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
    ports:
      - "15433:5432"
    volumes:
      - ./data/pg-res-data/data:/var/lib/postgresql/data
      - ./data/pg-res-data/app:/app
    working_dir: /app

networks:
  default:
    name: microbite-network