global using AuthServer.Data.Dto;
global using AuthServer.Data.Models;
global using AuthServer.Data.Repositories;
global using AuthServer.Service;
global using Isopoh.Cryptography.Argon2;
global using Microsoft.AspNetCore.Http;
global using NSubstitute;
global using Microsoft.Extensions.Logging;
global using NSubstitute.ExceptionExtensions;