name: Build Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: |
          cd frontend/MicroBiteClient
          npm install

      - name: Run build to check if it succeeds
        run: |
          cd frontend/MicroBiteClient
          npm run build
